### ISSUE TITLE
Nionui-tool does not compile on Mac OS

### ISSUE THREAD

**Issue by kociak** [nion-software/nionui-tool#1]
Hi
I cannot compile nionui-tool. Apparently, I am missing the right QT librairy (see below), but there are no instructions to install it.
Thanks for the help

`RuleScriptExecution /Users/mathieukociak/Downloads/nionui-tool-master\ 2/launcher/DocumentWindow.h normal x86_64 (in target: Nion UI Launcher)
    cd /Users/mathieukociak/Downloads/nionui-tool-master\ 2/launcher
    /bin/sh -c ${QTDIR}/bin/moc\ ${INPUT_FILE_PATH}\ >\ ${DERIVED_SOURCES_DIR}/${CURRENT_ARCH}/moc_${INPUT_FILE_BASE}.cpp

/bin/sh: /Users/mathieukociak/Developer/Qt/5.13.0/clang_64/bin/moc: No such file or directory
Command RuleScriptExecution failed with a nonzero exit code`

**Comment by cmeyer** [comment]
Travis CI is the definitive build - so you can work backwards from Travis to build on the Mac.

For example, see https://travis-ci.org/nion-software/nionui-tool/jobs/654731328

On my local machine I have the following modifications (you'll need to change QTDIR to point to your actual Qt installation)

```
diff --git a/launcher/xcconfig/targetDebugNionUILauncher.xcconfig b/launcher/xcconfig/targetDebugNionUILauncher.xcconfig
index 9187917..78a8ebf 100644
--- a/launcher/xcconfig/targetDebugNionUILauncher.xcconfig
+++ b/launcher/xcconfig/targetDebugNionUILauncher.xcconfig
@@ -1,5 +1,5 @@
 // set the base Qt version
-QTDIR = $(HOME)/Developer/Qt/5.13.0/clang_64
+QTDIR = $(HOME)/Developer/Qt/5.13.1/clang_64
 
 ARCHS = $(ARCHS_STANDARD_32_64_BIT)
 ONLY_ACTIVE_ARCH = YES
diff --git a/launcher/xcconfig/targetReleaseNionUILauncher.xcconfig b/launcher/xcconfig/targetReleaseNionUILauncher.xcconfig
index 069e3ef..1c74c0e 100644
--- a/launcher/xcconfig/targetReleaseNionUILauncher.xcconfig
+++ b/launcher/xcconfig/targetReleaseNionUILauncher.xcconfig
@@ -1,5 +1,5 @@
 // set the base Qt version
-QTDIR = $(HOME)/Developer/Qt/5.13.0/clang_64
+QTDIR = $(HOME)/Developer/Qt/5.13.1/clang_64
 
 ARCHS = x86_64
```
