### ISSUE TITLE
Build a macOS arm64 version of nionui-tool

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionui-tool#19]
Dependent on Qt. May also require #20 (Qt 6).

https://bugreports.qt.io/browse/QTBUG-87045

https://bugreports.qt.io/browse/QTBUG-85279

Also, follow along with conda-forge:

`CONDA_SUBDIR=osx-arm64 conda create -n py39-arm64-forge -c conda-forge nionswift pyqt`

`CONDA_SUBDIR=osx-arm64 conda create -n py39-arm64-forge -c conda-forge nionswift pyside2`

**Comment by cmeyer** [comment]
Pinging @TomaSusi.

**Comment by TomaSusi** [comment]
There already is a homebrew formula for pyqt:
https://formulae.brew.sh/formula/pyqt#default
