### ISSUE TITLE
nionui-tool not compatible with python 3.11

### ISSUE THREAD

**Issue by kociak** [nion-software/nionui-tool#42]
I made a developer install following the wiki.
Everything worked fine until I tried to conda install nion-tool. This wasn't possible because nion-tool was only compatible up to 3.10.
I tried to downgrade to 3.10 but it was a disaster.
I am now running with pyside2.
However, I am trying to track Thread issues with the Concurrent activities diagram, but it is damn slow and I wonder if this is because not using nion-tool.

**Comment by cmeyer** [comment]
nionui-tool and nionswift-tool 0.4.19 are now available across all channels with support for python 3.11 (but dropping support for python 3.8).
