### ISSUE TITLE
Include information in the built package to identify the build

### ISSUE THREAD

**Issue by cmeyer** [nion-software/nionui-tool#76]
Build date, Git hash, etc.

Make the info available at startup via a function or resource.

**Comment by cmeyer** [comment]
Implemented here
- nion-software/nionui-tool@b8a6d830f09e89bb14adc1aa5fb7f8574865700c
- nion-software/nionui@eee061aa49ab6dee08bad1131505726a794be32b

**Comment by Ion-e** [comment]
Verify as implemented. Will have a play with it in the next couple of weeks. Thanks!
